# Generated by Django 5.1.3 on 2024-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.TextField()),
                ('temperature', models.FloatField()),
                ('prompt', models.TextField()),
                ('response', models.TextField(null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
