# Generated by Django 5.1.3 on 2025-01-08 11:07

import studyPlannerAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlannerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', studyPlannerAPI.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='album_number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
