# Generated by Django 5.1.3 on 2025-03-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlannerAPI', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='message_type',
            field=models.CharField(default='question_answer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'subject'], name='studyPlanne_user_id_737a76_idx'),
        ),
    ]
