# Generated by Django 5.1.3 on 2025-03-14 19:42

import studyPlannerAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlannerAPI', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=studyPlannerAPI.models.user_directory_path),
        ),
    ]
