# Generated by Django 5.1.3 on 2025-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlannerAPI', '0005_studysession_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='elapsed_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
