# Generated by Django 5.1.3 on 2025-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlannerAPI', '0006_studysession_elapsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_model_preference',
            field=models.CharField(choices=[('deepseek', 'Deepseek AI'), ('gpt-4o', 'GPT-4o')], default='deepseek', max_length=20),
        ),
    ]
