# Generated by Django 5.1.3 on 2025-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlannerAPI', '0007_profile_ai_model_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ai_model_preference',
        ),
        migrations.AddField(
            model_name='studysession',
            name='ai_model',
            field=models.CharField(choices=[('deepseek', 'Deepseek AI'), ('gpt-4o', 'GPT-4o')], default='deepseek', max_length=20),
        ),
    ]
