# Generated by Django 5.1.3 on 2025-05-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlannerAPI', '0008_remove_profile_ai_model_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Komunikat o błędzie'),
        ),
        migrations.AddField(
            model_name='material',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Oczekujący'), ('processing', 'W trakcie przetwarzania'), ('completed', 'Przetworzony'), ('failed', 'Nieudany')], default='pending', max_length=20, verbose_name='Status przetwarzania PDF'),
        ),
    ]
